version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
    container_name: node-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
